# Generated by Django 5.2.7 on 2025-10-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('name', models.CharField(max_length=100, verbose_name="Customer's name")),
                ('address', models.TextField(verbose_name='Delivery address')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_menu.dish', verbose_name='Dish')),
            ],
        ),
    ]
