# Generated by Django 5.2.7 on 2025-10-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=2, max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
